fos_elastica:
  clients:
    default:
      host: heroku:4b4dfd4295ede7701a26a58588ce5e18@oin-us-east-1.searchly.com
      port: 443
  indexes:
    items:
      properties:
        id: ~
        name: ~
        tags: { type: "nested", properties: { name: ~ } }
        collection:
          type: "object"
          properties:
            id: ~
            name: ~
            description: ~
      persistence:
        driver: orm
        model: App\Entity\Item
        provider: ~
        finder: ~
