fos_elastica:
  clients:
    default:
      host: ivy-849219168.us-east-1.bonsaisearch.net
      port: 443
      username: 't6dufj6bh3'
      password: 't4b28ryclf'
  indexes:
    items:
      properties:
        id: ~
        name: ~
        tags: { type: "nested", properties: { name: ~ } }
        collection:
          type: "object"
          properties:
            id: ~
            name: ~
            description: ~
      persistence:
        driver: orm
        model: App\Entity\Item
        provider: ~
        finder: ~
